### ISSUE TITLE
Infografia Damaris 

### ISSUE THREAD

**Issue by DamGL** [SistemasTecTlaxiaco/infografia-DamGL#1]
[Infografia RA.pdf](https://github.com/SistemasTecTlaxiaco/infografia-DamGL/files/8138563/Infografia.RA.pdf)

**Comment by ThorSampy** [comment]
cumple con los puntos acordados y tiene buena presentación, calificación 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
